config/routes.rb
Rails.application.routes.draw do
  resources :nuevas
  get 'portada/publicar' => 'portada#publicar'
  get 'portada/deportes' => 'portada#deportes'
  get 'portada/nacional' => 'portada#nacional'
  get 'portada/farandula' => 'portada#farandula'
  get 'portada/internacional' => 'portada#internacional'
  get 'portada/politica' => 'portada#politica'
  get 'portada/index'
  root 'portada#index'
  get 'nuevas/index' => 'nuevas#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/nueva.rb
class Nueva < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/nuevas_controller.rb
class NuevasController < ApplicationController
  before_action :set_nueva, only: %i[ show edit update destroy ]

  # GET /nuevas or /nuevas.json
  def index
    @nuevas = Nueva.all
  end

  # GET /nuevas/1 or /nuevas/1.json
  def show
  end

  # GET /nuevas/new
  def new
    @nueva = Nueva.new
  end

  # GET /nuevas/1/edit
  def edit
  end

  # POST /nuevas or /nuevas.json
  def create
    @nueva = Nueva.new(nueva_params)

    respond_to do |format|
      if @nueva.save
        format.html { redirect_to nueva_url(@nueva), notice: "Nueva was successfully created." }
        format.json { render :show, status: :created, location: @nueva }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @nueva.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nuevas/1 or /nuevas/1.json
  def update
    respond_to do |format|
      if @nueva.update(nueva_params)
        format.html { redirect_to nueva_url(@nueva), notice: "Nueva was successfully updated." }
        format.json { render :show, status: :ok, location: @nueva }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @nueva.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nuevas/1 or /nuevas/1.json
  def destroy
    @nueva.destroy

    respond_to do |format|
      format.html { redirect_to nuevas_url, notice: "Nueva was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nueva
      @nueva = Nueva.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def nueva_params
      params.require(:nueva).permit(:encabezado, :cuerpo, :tipo)
    end
end

app/controllers/portada_controller.rb
class PortadaController < ApplicationController
  def publicar
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nuevas_helper.rb
module NuevasHelper
end

app/helpers/portada_helper.rb
module PortadaHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nicenews2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Nice News</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/portada/deportes">Deportes</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/portada/farandula">Farándula</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/portada/nacional">Nacional</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/portada/internacional">Internacional</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/portada/politica">Política</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/nuevas">Publicar Noticia</a>
          </li>
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Busqueda" aria-label="Buscar">
          <button class="btn btn-outline-success" type="submit">Buscar</button>
        </form>
      </div>
    </div>
  </nav>

  <%= yield %>


  <footer>
    <p>Integrantes: Alejandro Cofré - Jimena Aliaga - Jonathan Castro - Rolando Piñones - Yolanda Araya</p>
  </footer>
  </body>
</html>

app/views/nuevas/_form.html.erb
<%= form_with(model: nueva) do |form| %>
  <% if nueva.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(nueva.errors.count, "error") %> prohibited this nueva from being saved:</h2>

      <ul>
        <% nueva.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :encabezado, style: "display: block" %>
    <%= form.text_field :encabezado %>
  </div>

  <div>
    <%= form.label :cuerpo, style: "display: block" %>
    <%= form.text_field :cuerpo %>
  </div>

  <div>
    <%= form.label :tipo, style: "display: block" %>
    <%= form.number_field :tipo %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/nuevas/_nueva.html.erb
<div class="card">  
  <div id="<%= dom_id nueva %>">
    <p class="card-header">
      <strong>Encabezado:</strong>
      <%= nueva.encabezado %>
    </p>

    <p class="card-body">
      <strong>Cuerpo:</strong>
      <%= nueva.cuerpo %>
    </p>

    <p class="card-footer">
      <strong>Tipo:</strong>
      <%= nueva.tipo %>
    </p>
  </div>
</div>

app/views/nuevas/edit.html.erb
<h1>Editing nueva</h1>

<%= render "form", nueva: @nueva %>

<br>

<div>
  <%= link_to "Show this nueva", @nueva %> |
  <%= link_to "Back to nuevas", nuevas_path %>
</div>

app/views/nuevas/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Nice News</h1>

    <div id="nuevas">
      <div class="container text-center">
        <div class="row">
          <% @nuevas.each do |nueva| %>
            <div class="card bg-light col-2">
              <%= render nueva %>
              <p>
                <%= link_to "Mostrar esta noticia", nueva %>
              </p>
            </div>
          <% end %>
        </div>
      </div>
    </div>

<%= link_to "Nueva Noticia", new_nueva_path %>

app/views/nuevas/new.html.erb
<h1>New nueva</h1>

<%= render "form", nueva: @nueva %>

<br>

<div>
  <%= link_to "Back to nuevas", nuevas_path %>
</div>

app/views/nuevas/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @nueva %>

<div>
  <%= link_to "Edit this nueva", edit_nueva_path(@nueva) %> |
  <%= link_to "Back to nuevas", nuevas_path %>

  <%= button_to "Destroy this nueva", @nueva, method: :delete %>
</div>

app/views/portada/index.html.erb
<br>
<body>
    <header>
        <div class="container">
            <div class="row">
                <div class="card bg-secondary" style="width: 18rem; " >
                    <%= image_tag("deportes.jpg", :alt => "Deportes", :class => "card-img-top" ) %>
                    <div class="card-body">
                        <a href="/portada/deportes"> <h2 class="card-text">Deportes</h2> </a>
                    </div>
                </div>
                <div class="card bg-warning" style="width: 18rem; " >
                    <%= image_tag("farandula.jpg", :alt => "Farándula", :class => "card-img-top" ) %>
                    <div class="card-body">
                        <a href="/portada/farandula"> <h2 class="card-text">Farándula</h2> </a>
                    </div>
                </div>
                <div class="card bg-info" style="width: 18rem; " >
                    <%= image_tag("congreso.jpg", :alt => "Nacional", :class => "card-img-top" ) %>
                    <div class="card-body">
                        <a href="/portada/nacional"> <h2 class="card-text">Nacional</h2> </a>
                    </div>
                </div>
                <div class="card bg-success" style="width: 18rem; " >
                    <%= image_tag("internacional.jpg", :alt => "Internacional", :class => "card-img-top" ) %>
                    <div class="card-body">
                        <a href="/portada/internacional"> <h2 class="card-text">Internacional</h2> </a>
                    </div>
                </div>

            </div>
        </div>
    </header>
</body>

app/views/portada/internacional.html.erb
<h1>Portada#internacional</h1>
<p>Find me in app/views/portada/internacional.html.erb</p>

app/views/portada/nacional.html.erb
<h1>Portada#nacional</h1>
<p>Find me in app/views/portada/nacional.html.erb</p>

app/views/portada/politica.html.erb
<h1>Portada#politica</h1>
<p>Find me in app/views/portada/politica.html.erb</p>